version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  deploy-app:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - run:
          name: Deploy app to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

# jobs:
#   deploy-app:
#     steps:
#       - checkout
#       - run:
#           name: Run Tests
#           command: "cargo test"
